### ISSUE TITLE
Knowing the character for the first dialogue turn (dia1)

### ISSUE THREAD

**Issue by wise-east** [newpro/aloha-chatbot#4]
Is it possible to know the characters for `dia1` in `all_dialogs.csv` in `raw_data.zip`? I was able to find that about half of the `dia1`s are `dia2`s for other dialogue pairs, but for the rest I am unable to figure it out and was wondering if this information is accessible somehow. I am interested in grouping conversations that took place between two characters.

**Comment by newpro** [comment]
Sorry, the answer is that what you are looking at is all we have.

Thanks for the thoughts and details you have been putting into this. We were in an attempt to recover the "first person personality" and use it as further information to push performance further as our initial plan. We quickly realized that to do so, we have to either:

1) remove a lot of dialogues from training due to first-person minor roles needing more human-level features. We did a quick and raw data stress test on this. We observed that our dialogue data volume is too small, and the task ("zero-shot personality simulation," as cool kids now would call it) requires a high volume of dialogue data.

2) spending a crazy amount of time in further data collection to clean and collect more data. Notice this is only our opinion based on our data source at the time; maybe you can think about some methods that can approximate match between Human-level features and dialogue scripts.
